In [6]:
import numpy as np


def square(x):
    return x**2


square_np = np.vectorize(square)

print(square_np)
print(type(square_np))

# Test
numbers = [1, 2, 3, 4]

vector = square_np(numbers)
print(vector)
print(type(vector))

<class 'numpy.vectorize'>
[ 1  4  9 16]
<class 'numpy.ndarray'>


In [7]:
numbers = np.array([3, 4, 5])

square_numbers = numbers ** 2

print(square_numbers)

[ 9 16 25]


In [14]:
import numpy as np

zero_arr = np.zeros((2, 3))
print(zero_arr)

one_arr = np.ones((2, 3))
print(one_arr)

nine_arr = np.full((2, 3), 9)
print(nine_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[9 9 9]
 [9 9 9]]


In [18]:
eye_arr =  np.eye(3)
print(eye_arr)


random_arr = np.random.random((2, 3))
print(random_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.45386975 0.05771539 0.58837442]
 [0.59621942 0.03804224 0.84852179]]


In [21]:
a_range = np.arange(5)
print(a_range)

b_range = np.arange(0, 5, 2)
print(b_range)

[0 1 2 3 4]
[0 2 4]


In [24]:
data = np.arange(1, 7).reshape(2, 3)
print(data)
print('data shape', data.shape)

data_rs = data.reshape(3, 2)
print(data_rs)
print('data reshape', data_rs.shape)

[[1 2 3]
 [4 5 6]]
data shape (2, 3)
[[1 2]
 [3 4]
 [5 6]]
data reshape (3, 2)


In [28]:
flattened_data = data_rs.flatten()
print(flattened_data)

# Another way to flatten
flattened_2 = data_rs.reshape(-1)
print(flattened_2)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [32]:
import numpy as np

np.random.seed(42)
# Generate random integers
data = np.random.randint(1, 9, (2, 2))
print(data)

# Repeat data
data_repeat = data.repeat(2, axis=0)
print(data_repeat)

# Repeat by column
data_repeat_col = data.repeat(2, axis=1)
print(data_repeat_col)

[[7 4]
 [5 7]]
[[7 4]
 [7 4]
 [5 7]
 [5 7]]
[[7 7 4 4]
 [5 5 7 7]]


In [34]:
# Broadcasting
data = np.arange(1, 4)

double_data = data * 2
print(data)
print(double_data)

[1 2 3]
[2 4 6]


In [48]:
original = np.arange(1, 7).reshape(3, -1)
display('Original', original)

two = original[0, 1]
print(two, type(two), two.shape)

two_no_change_shape = original[0:1, 1:2]
print(two_no_change_shape, type(two_no_change_shape), two_no_change_shape.shape)

two_3 = original[0, 1:2]
print(two_3, type(two_3), two_3.shape)

'Original'

array([[1, 2],
       [3, 4],
       [5, 6]])

2 <class 'numpy.int32'> ()
[[2]] <class 'numpy.ndarray'> (1, 1)
[2] <class 'numpy.ndarray'> (1,)


In [50]:
original[1:3]

array([[3, 4],
       [5, 6]])

In [51]:
original[0:1, 0]

array([1])

In [56]:
import numpy as np

arr = np.arange(1, 10).reshape(3, 3)
print(arr)

col_1_ndim_decrease = arr[:, 1]
print(col_1_ndim_decrease, col_1_ndim_decrease.ndim)

col_1_ndim_unchanged = arr[:, 1:2]
print(col_1_ndim_unchanged, col_1_ndim_unchanged.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8] 1
[[2]
 [5]
 [8]] 2


In [57]:
# Get many values in one go
out1 = arr[[0, 1, 2], [0, 1, 0]]
print(out1)

[1 5 7]


In [61]:
condition = (arr <= 7) & (arr >=5)

print(condition)
print(arr[condition])

[[False False False]
 [False  True  True]
 [ True False False]]
[5 6 7]
